- path: output/game.mrs
  format: mrs
  behavior: domain
  upstream: &game_upstream
    game:
      type: http
      url: https://github.com/Harrykane-der/my-rules/raw/refs/heads/main/game.yaml
      format: yaml
      behavior: domain

- path: output/game.yaml
  format: yaml
  behavior: domain
  upstream: *game_upstream

- path: output/game.json
  format: json
  behavior: sing-box
  upstream: *game_upstream

- path: output/game.srs
  format: srs
  behavior: sing-box
  upstream: *game_upstream
  
- path: output/direct_emby.mrs
  format: mrs
  behavior: domain
  upstream: &direct_emby_upstream
    direct_emby:
      type: http
      url: https://github.com/Harrykane-der/my-rules/raw/refs/heads/main/direct_emby.yaml
      format: yaml
      behavior: domain

- path: output/direct_emby.yaml
  format: yaml
  behavior: domain
  upstream: *direct_emby_upstream

- path: output/direct_emby.json
  format: json
  behavior: sing-box
  upstream: *direct_emby_upstream

- path: output/direct_emby.srs
  format: srs
  behavior: sing-box
  upstream: *direct_emby_upstream
  
- path: output/proxy_emby.mrs
  format: mrs
  behavior: domain
  upstream: &proxy_emby_upstream
    proxy_emby:
      type: http
      url: https://github.com/Harrykane-der/my-rules/raw/refs/heads/main/proxy_emby.yaml
      format: yaml
      behavior: domain

- path: output/proxy_emby.yaml
  format: yaml
  behavior: domain
  upstream: *proxy_emby_upstream

- path: output/proxy_emby.json
  format: json
  behavior: sing-box
  upstream: *proxy_emby_upstream

- path: output/proxy_emby.srs
  format: srs
  behavior: sing-box
  upstream: *proxy_emby_upstream

- path: output/ablock.srs
  format: srs
  behavior: singbox
  upstream: &ablock_upstream
    ablock.json:
      type: http
      url: https://raw.githubusercontent.com/Harrykane-der/my-rules/refs/heads/main/ablock.json
      format: json
      behavior: singbox

- path: output/ablock.json
  format: json
  behavior: sing-box
  upstream: *ablock_upstream

# ablock
- path: output/adblock.mrs
  format: mrs
  behavior: domain
  upstream: &adblock_upstream
    adrules:
      type: http
      url: https://github.com/echs-top/proxy/raw/refs/heads/main/mrs/domain/ads.mrs
      format: mrs
      behavior: domain
    adblock:
      type: http
      url: https://github.com/Harrykane-der/AdRules/raw/refs/heads/main/adrules-mihomo.mrs
      format: mrs
      behavior: domain
    httpdns:
      type: http
      url: https://github.com/QuixoticHeart/rule-set/raw/refs/heads/ruleset/meta/domain/httpdns.mrs
      format: mrs
      behavior: domain
    category-ads-all:
      type: http
      url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-ads-all.mrs
      format: mrs
      behavior: domain
    reject:
      type: http
      url: https://github.com/SagerNet/sing-geosite/raw/refs/heads/rule-set/geosite-category-ads-all.srs
      format: srs
      behavior: singbox


- path: output/adblock.yaml
  format: yaml
  behavior: domain
  upstream: *adblock_upstream

- path: output/adblock.json
  format: json
  behavior: sing-box
  upstream: *adblock_upstream

- path: output/adblock.srs
  format: srs
  behavior: sing-box
  upstream: *adblock_upstream

# reject@ip
- path: output/adblock_ip.mrs
  format: mrs
  behavior: ipcidr
  upstream: &adblock_ip_upstream
    httpdns_ip:
      type: http
      url: https://github.com/QuixoticHeart/rule-set/raw/refs/heads/ruleset/meta/ipcidr/httpdns.mrs
      format: mrs
      behavior: ipcidr


- path: output/adblock_ip.yaml
  format: yaml
  behavior: ipcidr
  upstream: *adblock_ip_upstream

- path: output/adblock_ip.json
  format: json
  behavior: sing-box
  upstream: *adblock_ip_upstream

- path: output/adblock_ip.srs
  format: srs
  behavior: sing-box
  upstream: *adblock_ip_upstream


# direct
- path: output/cn.mrs
  format: mrs
  behavior: domain
  upstream: &cn_upstream
    MetaCubeX_cn:
      type: http
      url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/cn.yaml
      format: yaml
      behavior: domain      
    DustinWin_cn :
      type: http
      url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/cn.mrs
      format: mrs
      behavior: domain
    echs-top_cn:
      type: http
      url: https://github.com/echs-top/proxy/raw/refs/heads/main/list/domain/cn.list
      format: text
      behavior: domain 
    sb_cn:
      type: http
      url: https://github.com/SagerNet/sing-geosite/raw/refs/heads/rule-set/geosite-cn.srs
      format: srs
      behavior: singbox
    

- path: output/cn.yaml
  format: yaml
  behavior: domain
  upstream: *cn_upstream

- path: output/cn.json
  format: json
  behavior: sing-box
  upstream: *cn_upstream

- path: output/cn.srs
  format: srs
  behavior: sing-box
  upstream: *cn_upstream

# direct@ip
- path: output/cn_ip.mrs
  format: mrs
  behavior: ipcidr
  upstream: &cn_ip_upstream
    skk_domestic_ip:
      type: http
      url: https://ruleset.skk.moe/Clash/ip/domestic.txt
      format: text
      behavior: classical
    skk_china_ip:
      type: http
      url: https://ruleset.skk.moe/Clash/ip/china_ip.txt
      format: text
      behavior: ipcidr
    skk_china_ipv6:
      type: http
      url: https://ruleset.skk.moe/Clash/ip/china_ip_ipv6.txt
      format: text
      behavior: ipcidr
    DustinWin_cn_ip :
      type: http
      url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/cnip.list
      format: text
      behavior: ipcidr
    geoip_cn:
      type: http
      url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cn.yaml
      format: yaml
      behavior: ipcidr
    echs-top_cn_ip:
      type: http
      url: https://github.com/echs-top/proxy/raw/refs/heads/main/list/ip/cn.list
      format: text
      behavior: ipcidr
    sb_cn_ip:
      type: http
      url: https://github.com/SagerNet/sing-geoip/raw/refs/heads/rule-set/geoip-cn.srs
      format: srs
      behavior: singbox

- path: output/cn_ip.yaml
  format: yaml
  behavior: ipcidr
  upstream: *cn_ip_upstream

- path: output/cn_ip.json
  format: json
  behavior: sing-box
  upstream: *cn_ip_upstream

- path: output/cn_ip.srs
  format: srs
  behavior: sing-box
  upstream: *cn_ip_upstream

# microsoft@cn
- path: output/microsoft@cn.mrs
  format: mrs
  behavior: domain
  upstream: &microsoft_cn_upstream
    skk_microsoft_cdn:
      type: http
      url: https://ruleset.skk.moe/Clash/non_ip/microsoft_cdn.txt
      format: text
      behavior: classical
    DustinWin_microsoft_cn:
      type: http
      url: https://github.com/DustinWin/domain-list-custom/releases/download/domains/microsoft-cn.list
      format: text
      behavior: classical
    local_microsoft_cn:
      type: file
      path: local/microsoft@cn.yaml
      format: yaml
      behavior: classical

- path: output/microsoft@cn.yaml
  format: yaml
  behavior: domain
  upstream: *microsoft_cn_upstream

- path: output/microsoft@cn.json
  format: json
  behavior: sing-box
  upstream: *microsoft_cn_upstream

- path: output/microsoft@cn.srs
  format: srs
  behavior: sing-box
  upstream: *microsoft_cn_upstream

# apple@cn
- path: output/apple@cn.mrs
  format: mrs
  behavior: domain
  upstream: &apple_cn_upstream
    skk_apple_services:
      type: http
      url: https://ruleset.skk.moe/Clash/non_ip/apple_services.txt
      format: text
      behavior: classical
    skk_apple_cn:
      type: http
      url: https://ruleset.skk.moe/Clash/non_ip/apple_cn.txt
      format: text
      behavior: classical
    skk_apple_cdn:
      type: http
      url: https://ruleset.skk.moe/Clash/domainset/apple_cdn.txt
      format: text
      behavior: domain
    DustinWin_apple_cn:
      type: http
      url: https://github.com/DustinWin/domain-list-custom/releases/download/domains/apple-cn.list
      format: text
      behavior: classical

- path: output/apple@cn.yaml
  format: yaml
  behavior: domain
  upstream: *apple_cn_upstream

- path: output/apple@cn.json
  format: json
  behavior: sing-box
  upstream: *apple_cn_upstream

- path: output/apple@cn.srs
  format: srs
  behavior: sing-box
  upstream: *apple_cn_upstream

# steam@cn
- path: output/steam@cn.mrs
  format: mrs
  behavior: domain
  upstream: &steam_cn_upstream
    blackmatrix7_steam_cn:
      type: http
      url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/SteamCN/SteamCN.yaml
      format: yaml
      behavior: classical

- path: output/steam@cn.yaml
  format: yaml
  behavior: domain
  upstream: *steam_cn_upstream

- path: output/steam@cn.json
  format: json
  behavior: sing-box
  upstream: *steam_cn_upstream

- path: output/steam@cn.srs
  format: srs
  behavior: sing-box
  upstream: *steam_cn_upstream

# ai
- path: output/ai.mrs
  format: mrs
  behavior: domain
  upstream: &ai_upstream
    DustinWin_ai:
      type: http
      url: https://github.com/DustinWin/domain-list-custom/releases/download/domains/ai.list
      format: text
      behavior: classical
    ACL4SSR_ai:
      type: http
      url: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Ruleset/AI.list
      format: text
      behavior: classical
    local_ai:
      type: file
      path: local/ai.yaml
      format: yaml
      behavior: classical

- path: output/ai.yaml
  format: yaml
  behavior: domain
  upstream: *ai_upstream

- path: output/ai.json
  format: json
  behavior: sing-box
  upstream: *ai_upstream

- path: output/ai.srs
  format: srs
  behavior: sing-box
  upstream: *ai_upstream

# proxy
- path: output/gfw.mrs
  format: mrs
  behavior: domain
  upstream: &gfw_upstream
    skk_cdn_domainset:
      type: http
      url: https://ruleset.skk.moe/Clash/domainset/cdn.txt
      format: text
      behavior: domain
    skk_cdn:
      type: http
      url: https://ruleset.skk.moe/Clash/non_ip/cdn.txt
      format: text
      behavior: classical
    skk_stream:
      type: http
      url: https://ruleset.skk.moe/Clash/non_ip/stream.txt
      format: text
      behavior: classical
    telegram:
      type: http
      url: https://ruleset.skk.moe/Clash/non_ip/telegram.txt
      format: text
      behavior: classical
    skk_download_domainset:
      type: http
      url: https://ruleset.skk.moe/Clash/domainset/download.txt
      format: text
      behavior: domain
    skk_download:
      type: http
      url: https://ruleset.skk.moe/Clash/non_ip/download.txt
      format: text
      behavior: classical
    skk_global:
      type: http
      url: https://ruleset.skk.moe/Clash/non_ip/global.txt
      format: text
      behavior: classical
    xndeye_proxy:
      type: file
      path: local/proxy.yaml
      format: yaml
      behavior: classical
    gfw:
      type: http
      url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/gfw.mrs
      format: mrs
      behavior: domain
    google_cn:
      type: http
      url: https://github.com/DustinWin/domain-list-custom/releases/download/domains/google-cn.list
      format: text
      behavior: classical
    skk_biliintl:
      type: http
      url: https://ruleset.skk.moe/Clash/non_ip/stream_biliintl.txt
      format: text
      behavior: classical
    DustinWin_proxy:
      type: http
      url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/proxy.mrs
      format: mrs
      behavior: domain
    DustinWin_madia:
      type: http
      url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/media.mrs
      format: mrs
      behavior: domain
    DustinWin_gfw:
      type: http
      url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/gfw.mrs
      format: mrs
      behavior: domain
    MetaCubeX_tld-!cn:
      type: http
      url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/tld-!cn.mrs
      format: mrs
      behavior: domain
    MetaCubeX_geolocation-!cn:
      type: http
      url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/geolocation-!cn.mrs
      format: mrs
      behavior: domain
    MetaCubeX_gfw:
      type: http
      url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/gfw.mrs
      format: mrs
      behavior: domain


- path: output/gfw.yaml
  format: yaml
  behavior: domain
  upstream: *gfw_upstream


- path: output/gfw.json
  format: json
  behavior: sing-box
  upstream: *gfw_upstream

- path: output/gfw.srs
  format: srs
  behavior: sing-box
  upstream: *gfw_upstream

# proxy@ip
- path: output/gfw_ip.mrs
  format: mrs
  behavior: ipcidr
  upstream: &gfw_ip_upstream
    skk_stream_ip:
      type: http
      url: https://ruleset.skk.moe/Clash/ip/stream.txt
      format: text
      behavior: classical
    skk_telegram_ip:
      type: http
      url: https://ruleset.skk.moe/Clash/ip/telegram.txt
      format: text
      behavior: classical
    skk_cdn_ip:
      type: http
      url: https://ruleset.skk.moe/Clash/ip/cdn.txt
      format: text
      behavior: classical

- path: output/gfw_ip.yaml
  format: yaml
  behavior: ipcidr
  upstream: *gfw_ip_upstream

- path: output/gfw_ip.json
  format: json
  behavior: sing-box
  upstream: *gfw_ip_upstream

- path: output/gfw_ip.srs
  format: srs
  behavior: sing-box
  upstream: *gfw_ip_upstream

# lan@ip
- path: output/lan@ip.mrs
  format: mrs
  behavior: ipcidr
  upstream: &lan_ip_upstream
    private:
      type: http
      url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/private.yaml
      format: yaml
      behavior: ipcidr

- path: output/lan@ip.yaml
  format: yaml
  behavior: ipcidr
  upstream: *lan_ip_upstream

- path: output/lan@ip.json
  format: json
  behavior: sing-box
  upstream: *lan_ip_upstream

- path: output/lan@ip.srs
  format: srs
  behavior: sing-box
  upstream: *lan_ip_upstream

# lan
- path: output/lan.mrs
  format: mrs
  behavior: domain
  upstream: &lan_upstream
    skk_lan:
      type: http
      url: https://ruleset.skk.moe/Clash/non_ip/lan.txt
      format: text
      behavior: classical

- path: output/lan.yaml
  format: yaml
  behavior: domain
  upstream: *lan_upstream

- path: output/lan.json
  format: json
  behavior: sing-box
  upstream: *lan_upstream

- path: output/lan.srs
  format: srs
  behavior: sing-box
  upstream: *lan_upstream

# fakeip-filter
- path: output/fakeip-filter.mrs
  format: mrs
  behavior: domain
  upstream: &fakeip_filter_upstream
    skk_fake_ip_filter:
      type: http
      url: https://ruleset.skk.moe/Clash/domainset/clash_fake_ip_filter.txt
      format: text
      behavior: domain
    DustinWin_fake_ip_filter:
      type: http
      url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/fakeip-filter.list
      format: text
      behavior: classical
    QuixoticHeart_fake_ip_filter:
      type: http
      url: https://github.com/QuixoticHeart/rule-set/raw/refs/heads/ruleset/meta/domain/media.list
      format: text
      behavior: domain
    wwqgtxx_fakeip-filter:
      type: http
      url: https://raw.githubusercontent.com/wwqgtxx/clash-rules/release/fakeip-filter.mrs
      format: mrs
      behavior: domain
    Harrykane-der_fake_ip_filter:
      type: http
      url: https://github.com/Harrykane-der/my-rules/raw/refs/heads/main/fakeip-filter.yaml
      format: yaml
      behavior: domain
      
    

- path: output/fakeip-filter.yaml
  format: yaml
  behavior: domain
  upstream: *fakeip_filter_upstream

- path: output/fakeip-filter.json
  format: json
  behavior: sing-box
  upstream: *fakeip_filter_upstream

- path: output/fakeip-filter.srs
  format: srs
  behavior: sing-box
  upstream: *fakeip_filter_upstream
  
- path: output/media.mrs
  format: mrs
  behavior: domain
  upstream: &media_upstream
    DustinWin_media:
      type: http
      url: https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/media.mrs
      format: mrs
      behavior: domain
    MetaCubeX_media:
      type: http
      url: https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-media.mrs
      format: mrs
      behavior: domain

- path: output/media.yaml
  format: yaml
  behavior: domain
  upstream: *media_upstream

- path: output/media.json
  format: json
  behavior: sing-box
  upstream: *media_upstream

- path: output/media.srs
  format: srs
  behavior: sing-box
  upstream: *media_upstream
